Repository ZsgsDesign/NOJ, pull requests merged in 2019-03, with the labels that each got.

#27 a small change but can always benefit from it
  resources/views/layouts/app.blade.php
Labels: enhancement

#36 add migration for NOJ
  README.md
Labels: Enhancement

#38 Update README.md
  README.md
Labels: Enhancement

#39 dynamically display support OJ
  app/Http/Controllers/MainController.php
  resources/views/home.blade.php
Labels: Enhancement

#42 make contest detail page's image dynamic
  resources/views/contest/detail.blade.php
Labels: Enhancement, Priority 3 (Medium)

#51 better pagination and a simple judgment
  app/Http/Controllers/ContestController.php
  app/Http/Controllers/ProblemController.php
  app/Models/ContestModel.php
  app/Models/ProblemModel.php
  resources/views/contest/index.blade.php
  resources/views/problem/index.blade.php
Labels: Enhancement, Priority 3 (Medium)

#62 Fix the step number error in README
  README.md
Labels: Bug, Priority 3 (Medium)

#63 Scrutinizer Auto-Fixes
  app/Http/Controllers/Ajax/ContestController.php
  app/Http/Controllers/Ajax/ProblemController.php
  app/Http/Controllers/VirtualJudge/Judge.php
  app/Models/ContestModel.php
  app/Models/ProblemModel.php
  app/Models/SubmissionModel.php
Labels: Priority 3 (Medium)
